version: '3.1'
services:
  db:
    image: mysql
    container_name: chunim_with_spring
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root

    ports:
      - "3306:3306"

    volumes:
      - refactored_chunim_data:/var/lib/mysql

volumes:
  refactored_chunim_data:

