server:
  error:
    include-stacktrace: on_param
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root

    tomcat:
      test-while-idle: true
      validation-query: SELECT 1


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  jackson:
    serialization.write-dates-as-timestamps: false
    serialization.write-dates-with-zone-id: true



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG